(function(){'use strict';var f;var h=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},l=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null};var m=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d};function n(){this.s={}}n.prototype.add=function(a,b){a="string"==typeof a?a:a.getString();this.s[a]||(this.s[a]=[]);this.s[a].push(b)};var p=function(a){var b=[],c="object"==typeof gwd&&"GwdId"in gwd,d;for(d in a.s)b.push(c?new gwd.GwdId(d):d);return b},q=function(a,b){return b?a.s["string"==typeof b?b:b.getString()]||[]:[]};function r(a,b){this.g=a;this.T=b;this.C=this.H.bind(this)}r.prototype.observe=function(a){if(a.nodeType==Node.ELEMENT_NODE)for(var b=p(this.g),c=0;c<b.length;c++){var d=t(b[c]);if(d&&h(a,d)){var e=q(this.g,b[c]);e&&e.forEach(function(a){d.addEventListener(a.event,this.C,!1)}.bind(this))}}};var u=function(a,b){if(b.nodeType==Node.ELEMENT_NODE)for(var c=p(a.g),d=0;d<c.length;d++){var e=t(c[d]);if(e&&h(b,e)){var g=q(a.g,c[d]);g&&g.forEach(function(a){e.removeEventListener(a.event,this.C,!1)}.bind(a))}}};
r.prototype.H=function(a){this.T(a)};var t=function(a){return"string"==typeof a?document.getElementById(a):a.getElement(document)};document.registerElement("gwd-metric-event");document.registerElement("gwd-metric-configuration");document.registerElement("gwd-exit");document.registerElement("gwd-timer");var w=function(){};goog.inherits(w,HTMLElement);f=w.prototype;
f.createdCallback=function(){document.body.style.opacity="0";this.N=this.$.bind(this);this.F=this.ba.bind(this);this.O=this.aa.bind(this);this.w=this.Z.bind(this);this.v=this.X.bind(this);this.A=m.bind(null,"expandfinish",this);this.u=m.bind(null,"collapsefinish",this);this.M=this.Y.bind(this);this.C=this.H.bind(this);this.R=this.ca.bind(this);this.S=this.da.bind(this);this.f=null;this.m=this.o=!1;this.I=[];this.l=!1;this.J=this.hasAttribute("fullscreen");this.j=null;this.B=this.h=!1;this.D=window.innerHeight>=
window.innerWidth?1:2;this.L=this.b=null};
f.attachedCallback=function(){Enabler.addEventListener(studio.events.StudioEvent.EXPAND_START,this.w);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_START,this.v);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.w);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,this.v);Enabler.addEventListener(studio.events.StudioEvent.EXPAND_FINISH,this.A);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.u);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,
this.A);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.u);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.M);this.a=this.querySelector("[is=gwd-pagedeck]");this.a.addEventListener("pagetransitionend",this.R,!1);this.b=document.getElementById(this.getAttribute("data-provider"));this.L=document.getElementById(this.getAttribute("data-provider"));var a=this.querySelector("gwd-metric-configuration"),b=new n;if(a){a=Array.prototype.slice.call(a.getElementsByTagName("gwd-metric-event"));
for(var c=0;c<a.length;c++){var d=a[c],e=d.getAttribute("source");if(e){var g=d.getAttribute("exit");d={event:d.getAttribute("event"),ea:d.getAttribute("metric")||g,U:d.hasAttribute("cumulative"),exit:g};b.add(x(e),d)}}}this.g=b;this.P=new r(this.g,this.C);window.addEventListener("resize",this.S,!1)};
f.detachedCallback=function(){Enabler.removeEventListener(studio.events.StudioEvent.INIT,this.N);Enabler.removeEventListener(studio.events.StudioEvent.VISIBLE,this.F);Enabler.removeEventListener(studio.events.StudioEvent.PAGE_LOADED,this.O);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_START,this.w);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_START,this.v);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.w);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,
this.v);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_FINISH,this.A);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.u);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.A);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.u);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.M);this.a.removeEventListener("pagetransitionend",this.R,!1);window.removeEventListener("resize",
this.S,!1);this.b&&this.f&&this.b.removeEventListener("ready",this.f)};f.initAd=function(){this.l=!1;var a=this.N;Enabler.removeEventListener(studio.events.StudioEvent.INIT,a);Enabler.addEventListener(studio.events.StudioEvent.INIT,a);Enabler.isInitialized()&&a()};f.exit=function(a,b,c,d,e){Enabler.exit(a,b);("undefined"==typeof d||d)&&y(this);c&&this.goToPage(e)};f.exitOverride=function(a,b,c,d,e){Enabler.exitOverride(a,b);("undefined"==typeof d||d)&&y(this);c&&this.goToPage(e)};
f.incrementCounter=function(a,b){Enabler.counter(a,b)};f.startTimer=function(a){Enabler.startTimer(a)};f.stopTimer=function(a){Enabler.stopTimer(a)};f.reportManualClose=function(){Enabler.reportManualClose()};
f.H=function(a){var b=a.target,c=x(b),d=c+": "+a.type;a:{var e=q(this.g,c);for(var g=0;g<e.length;g++)if(e[g].event==a.type){e=e[g];break a}e=void 0}e.exit&&a.detail&&a.detail.url?(d=c+": "+e.exit,a.detail["exit-id"]&&(d=a.detail["exit-id"]),b="",null!=a.detail["product-index"]&&(b=a.detail["product-index"]),this.b&&"dynamic_remarketing"==this.L.getAttribute("gwd-schema-id")?(c=a.detail["action-event"],e={},c&&(e.clickX=c.clientX||c.changedTouches[0].clientX,e.clickY=c.clientY||c.changedTouches[0].clientY),
Enabler.dynamicExit(d,a.detail.url,b,void 0,e)):Enabler.exitOverride(d,a.detail.url),a.detail.handled=!0,a.detail.collapse&&this.goToPage()):(a=l(b))&&a.gwdIsActive()&&this.incrementCounter(e.ea||d,e.U)};
f.$=function(){var a=function(){if(this.hasAttribute("polite-load")){var a=this.O;Enabler.isPageLoaded()?a():Enabler.addEventListener(studio.events.StudioEvent.PAGE_LOADED,a)}else a=this.F,Enabler.isVisible()?a():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,a)}.bind(this);if(this.J){var b=function(c){(this.j=!!c.supported)&&m("fullscreensupport",this);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,b);a()}.bind(this);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,
b);Enabler.queryFullscreenSupport()}else a()};f.ba=function(a){if(this.l)this.b&&z(this);else{if(a)var b=a.detail;var c=this.ha.bind(this,b);this.b&&(c=this.W.bind(this,c));if(this.J){Enabler.setResponsiveExpanding(!0);var d=function(a){this.B=a;c()}.bind(this);Enabler.loadModule(studio.module.ModuleId.GDN,function(){var a=studio.sdk.gdn.getConfig();a.isInCreativeToolsetContext()?a.isInterstitial(d):c()})}else c()}};
f.aa=function(){var a=this.F;Enabler.isVisible()?a():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,a)};f.W=function(a){this.b?(this.f&&this.b.removeEventListener("ready",this.f),this.f=this.fa.bind(this,a),this.b.isDataLoaded()&&this.f(),this.b.addEventListener("ready",this.f)):a()};f.fa=function(a){z(this);a()};
var z=function(a){var b=document.getElementsByTagName("gwd-data-binder");if(0<b.length){b=b[0];var c=a.b.getData();if(c){var d=a.a.getElementsBySelector("*");d=d.concat(a.a.getPages());b.bindData(c,d);a.l&&(a=document.getElementsByTagName("gwd-text-helper"),0<a.length&&a[0].refitAll())}}};f=w.prototype;f.ha=function(a){this.l||(this.l=!0,document.body.style.opacity="",m("adinitialized",this,a),this.B?(a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0)),this.goToPage(a.id)):this.goToPage())};
f.goToPage=function(a,b,c,d,e){var g=this.a.getPage(this.a.currentIndex);if(a=a?this.a.getPage(a):this.a.getDefaultPage()){var v=!!g&&!!a&&!this.o&&!this.B&&!g.hasAttribute("expanded")&&a.hasAttribute("expanded");g=!!g&&!!a&&!this.m&&!this.B&&g.hasAttribute("expanded")&&!a.hasAttribute("expanded");v&&this.m||g&&this.o||((this.c=a.id,b&&(this.i={transition:b,duration:c,V:d,direction:e}),v)?this.J&&!1!==this.j?this.j&&(this.h=!0,Enabler.requestFullscreenExpand()):Enabler.requestExpand():g?this.h?Enabler.requestFullscreenCollapse():
Enabler.requestCollapse():(this.m=this.o=!1,this.G()))}};f.Z=function(){m("expandstart",this);this.j?(this.h=!0,Enabler.finishFullscreenExpand()):Enabler.finishExpand();if(!this.c){var a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0));a&&(this.c=a.id)}a=this.a.getPage(this.a.currentIndex);this.o=!!a&&this.c!=a.id;setTimeout(this.G.bind(this),30)};
f.X=function(){m("collapsestart",this);this.h?(Enabler.finishFullscreenCollapse(),this.h=!1):Enabler.finishCollapse();this.c||(this.reportManualClose(),this.c=this.a.getDefaultPage().id);var a=this.a.getPage(this.a.currentIndex);this.m=!!a&&this.c!=a.id;setTimeout(this.G.bind(this),30)};f.da=function(){if(!this.c){var a=window.innerHeight>=window.innerWidth?1:2;this.D!=a&&(this.D=a,(a=this.a.getPage(this.a.currentIndex))&&setTimeout(this.goToPage.bind(this,a.id),0))}};
f.Y=function(a){a&&Enabler.setResponsiveSize(a.width,a.height)};f.G=function(){if(this.c){this.D=window.innerHeight>=window.innerWidth?1:2;var a=this.a.getOrientationSpecificPage(this.D,this.c);this.i?this.a.goToPage(a.id,this.i.transition,this.i.duration,this.i.V,this.i.direction):this.a.goToPage(a.id);this.h&&a.classList.add("fs")}this.i=this.c=void 0};
f.ca=function(a){this.m=this.o=!1;if(a.target==this.a){var b=a.detail;a=b.outgoingPage;b=b.incomingPage;if(a&&(u(this.P,a),(a=a.querySelectorAll("video"))&&0<a.length))for(this.K=[];this.I.length;)studio.video.Reporter.detach(this.I.shift());this.P.observe(b);if((a=b.querySelectorAll("video"))&&0<a.length){b=studio.video&&studio.video.Reporter;var c=this.ga.bind(this);this.K=Array.prototype.slice.call(a);b?c():Enabler.loadModule(studio.module.ModuleId.VIDEO,c)}}};
f.ga=function(){for(var a,b;this.K.length;)if(b=this.K.shift(),a=x(b))studio.video.Reporter.attach(a,b,b.autoplay),this.I.push(a)};var x=function(a){return"object"==typeof gwd&&"GwdId"in gwd?(new gwd.GwdId(a)).getString():"string"==typeof a?a:a.id},y=function(a){Array.prototype.slice.call(a.a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})};w.prototype.attributeChangedCallback=function(){};document.registerElement("gwd-doubleclick",{prototype:w.prototype});}).call(this);
